name: youtuber-bidding-app
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
      - /app/node_modules
    env_file:
      - ../env/.env.dev
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_PUBLIC_API_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - youtuber-bidding
    command: sh -c "npm install @sveltejs/adapter-auto && npm run dev -- --host 0.0.0.0"

networks:
  youtuber-bidding:
    external: true